const { client } = require('./var_dump');

function uuidv4() {
    return 'gen-xxxxx-xxxx-4xxx-yxxx-xxxxxxx-week'.replace(/[xy]/g, function (c) {
        var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
        return v.toString(16);
    });
}

function uuidv5() {
    return 'gen-xxxxx-xxxx-4xxx-yxxx-xxxxxxx-month'.replace(/[xy]/g, function (c) {
        var r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
        return v.toString(16);
    });
}

function rScriptsv1() {
    const scriptrotation = ['week', 'week', 'week'];

    return scriptrotation[Math.floor(Math.random() * scriptrotation.length)]
}

function rScriptsv2() {
    const scriptrotation = ['month', 'month', 'month'];

    return scriptrotation[Math.floor(Math.random() * scriptrotation.length)]
}


function DBLicenseEntry(entries, message) {
    let sqlitems = [], sql

    console.log("generating entries");

    for (i = 1; i <= entries; i++) {
        sqlitems.push({ id: uuidv4(), script: rScriptsv1() });
    }

    console.log("entries have been generated");
    console.log("preparing SQL statement");
    message.author.send("Here are you're key(s) bby")
    sql = "INSERT INTO `keys` (`licensekeys`, `timestamp`) VALUES"
    sqlitems.map((item, index) => {
        index === 0 ? sql += ` ('${item.id}', '${item.script}')` : sql += `, ('${item.id}', '${item.script}')`
        message.author.send("```Gen Week key: " + item.id + "```")
        client.channels.cache.get(`935552478798299246`).send(`Key: ${item.id} has been generated by: <@${message.author.id}> `)
    });
    message.reply('you can find the keys in your pm!')
    console.log("sql prepared")

    return sql;
}

function DBLicenseEntry2(entries, message) {
    let sqlitems = [], sql

    console.log("generating entries");

    for (i = 1; i <= entries; i++) {
        sqlitems.push({ id: uuidv5(), script: rScriptsv2() });
    }

    console.log("entries have been generated");
    console.log("preparing SQL statement");
    message.author.send("Here are you're key(s) bby")
    sql = "INSERT INTO `keys` (`licensekeys`, `timestamp`) VALUES"
    sqlitems.map((item, index) => {
        index === 0 ? sql += ` ('${item.id}', '${item.script}')` : sql += `, ('${item.id}', '${item.script}')`
        message.author.send("```Gen Month key: " + item.id + "```")
        client.channels.cache.get(`935552478798299246`).send(`Key: ${item.id} has been generated by: <@${message.author.id}> `)
    });
    message.reply('you can find the keys in your pm!')
    console.log("sql prepared")

    return sql;
}



module.exports = { DBLicenseEntry, DBLicenseEntry2 };